version: "3.7"

services:
  schift-scheduing-bot:
    image: ghcr.io/danygold/shift-scheduling-bot:master
    environment:
      TELEGRAM_TOKEN: telegram_token_here
      BOT_NAME: bot_name_here
      ADMIN_USERS: admin_users_here
      DATA_DIR: /data
    restart: unless-stopped
    volumes:
      - "./data:/data"